- name: Golang echo server
  hosts: all
  become: yes
  tasks:
    - name: set golang URL
      set_fact:
        golang_url: "https://golang.org/dl/go1.17.3.linux-amd64.tar.gz"

    - name: set src directory
      set_fact:
        task2_src: /home/mftiedu/dnet/task2_src

    - name: create task2 src directory task2_src
      file: state=directory path={{ task2_src }}

    - name: download golang src
      get_url: url={{ golang_url }} dest={{ task2_src }}

    - name: copy the src files
      copy:
        src: "{{ playbook_dir }}/task2_src/"
        dest: "{{ task2_src }}"

    - name: install application
      command: sh {{ task2_src }}/install.sh

    - name: run application
      command: sh {{ task2_src }}/run.sh

    - name: stop application
      command: sh {{ task2_src }}/stop.sh
